### ISSUE TITLE
Add Installation Instructions to ReadMe

### ISSUE THREAD

**Issue by seunzone** [PaulKariukiRimiru/Team-timer#12]
This is a really cool product. It looks like what a lot of teams can work with whilst delivering stand-ups or in a meeting.
Can you kindly add installation instructions to the readme of how to do the following:
- Start application
- Connect to a database
- Deploy App
- Change countdown timer range

🔥

**Comment by paulrimiru** [comment]
Thanks, a PR for this issue will be up soon
